name: Release Application

permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - "release/*"
  workflow_dispatch:

jobs:
  build_for_release:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true

      - name: Sync UV
        run: uv sync --locked --all-extras --dev

      - name: Build
        run: |
          uv run pyinstaller -y --onefile -n "main.${{ matrix.os }}.exe" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: "${{ matrix.os }}.exe"
          path: "dist/main.${{ matrix.os }}.exe"
          if-no-files-found: "error"

  github_release:
    runs-on: ubuntu-latest
    needs: build_for_release
    steps:
      - name: get built artifacts
        uses: actions/download-artifact@v8
        with:
          skip-decompress: true

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: true
          files: |
            macos-latest.exe/macos-latest.exe.zip
            windows-latest.exe/windows-latest.exe.zip