name: Release Application

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  prep_for_release:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Version
        run: |
#          uv version --bump=patch
#          git commit -am "[build] bump minor version"
#          version="$(uv version --short)"
#          tagname="release/$version"
#          git tag "$tagname"

  build_for_release:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true

      - name: Sync UV
        run: uv sync --locked --all-extras --dev

      - name: Build
        run: |
          uv run pyinstaller -y --onefile -n "main.${{ matrix.os }}.exe" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: main-windows
          path: "dist/main.${{ matrix.os }}.exe"

  github_release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v3